/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AwsAccessKeyId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AwsRegion": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AwsSecretAccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LiveblocksPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LiveblocksSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}